apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlcube-workspace
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/demo/k8s_workspace

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlcube-workspace
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
